name: last_rpg_client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.7.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/characters/
    - assets/images/stages/
    - assets/images/bars/
    - assets/images/battle/

  fonts:
    - family: DIN
      fonts:
        - asset: assets/fonts/DIN-Alternate-Bold.ttf
